--MODEL AS OF 02/23/2026
--EMPLOYEE IMPORT
SELECT
	E.DATA_FOLDER_ID AS DONOTIMPORT,
	CONCAT('LEGACY_ID: ',E.EMPLOYEE) AS DONOTIMPORT,
	CONCAT('LEGACY_NAME: ', E.EMPLOYEE_NAME) AS DONOTIMPORT,
	CONCAT('LEGACY_STATUS: ', CASE WHEN E.Termination_Date IS NULL THEN 'Active' ELSE 'Inactive' END) AS DONOTIMPORT,
	SE.NEW_EMPLOYEE_ID AS EMPLOYEE_ID,
	--'' AS EMPLOYEE_ID,
	'Full Time' AS EMPLOYEE_TYPE,
	E.DATA_FOLDER_ID + ' ' + E.EMPLOYEE AS LEGACY_EMPLOYEE_ID,
	E.TITLE AS JOB_TITLE,
	E.SOCIAL_SECURITY_NUMBER AS SSNO,
	COALESCE(FORMAT(E.BIRTH_DATE, 'yyyy-MM-dd'),'') AS BIRTH_DATE,
	COALESCE(FORMAT(COALESCE(E.REHIRE_DATE, E.HIRE_DATE), 'yyyy-MM-dd'),'') AS START_DATE,
	CASE WHEN E.TERMINATION_DATE IS NULL THEN '' ELSE FORMAT(E.TERMINATION_DATE, 'yyyy-MM-dd') END AS END_DATE,
	--'-' AS DEPT_ID,
	TE.NEW_ENTITY_ID AS LOCATION_ID,
	'' AS CLASS_ID,
	E.GENDER AS GENDER,
	'' AS SUPERVISOR_ID,
	REPLACE(E.EMPLOYEE_NAME,';', ',') AS CONTACT_NAME,
	CASE WHEN E.TERMINATION_DATE IS NULL THEN 'T' ELSE 'F' END AS ACTIVE,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.MI,
	E.DATA_FOLDER_ID AS COMPANY_NAME,
	E.FIRST_NAME + ' ' + CASE WHEN E.MI ='' THEN '' ELSE E.MI + ' ' END + E.LAST_NAME AS PRINT_AS,
	E.PHONE_NUMBER AS PHONE1,
	E.EMAIL_ADDRESS AS EMAIL1,
	E.MOBILE_PHONE AS CELLPHONE,
	E.ADDRESS_1 AS ADDRESS1,
	E.ADDRESS_2 AS ADDRESS2,
	E.CITY AS CITY,
	E.STATE AS STATE,
	E.ZIP_CODE AS ZIP,
	E.DEPARTMENT AS DONOTIMPORT,
	E.CERTIFIED_CLASS AS DONOTIMPORT,
	E.UNION_ID AS DONOTIMPORT,
	E.UNION_LOCAL AS DONOTIMPORT,
	E.UNION_CLASS AS DONOTIMPORT
FROM
	[MAP].[T_MASTER_EMPLOYEE] E
	LEFT JOIN [MAP].[T_TRANS_EMPLOYEE] SE ON E.EMPLOYEE = SE.LEGACY_EMPLOYEE_ID AND E.DATA_FOLDER_ID = SE.DATA_FOLDER_ID
	LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON E.Data_Folder_Id = TE.DATA_FOLDER_ID
--WHERE
--	SE.INCLUDE_EMPLOYEE = 1
ORDER BY
	E.EMPLOYEE_NAME,
	E.EMPLOYEE;
