SELECT
	BA.Data_Folder_Id AS DONOTIMPORT,
	BA.Account_Type AS DONOTIMPORT,
	BA.Bank_Account AS ACCOUNT_ID,
	BA.Account_Number AS ACCOUNT_NUMBER,
	BA.Bank_Name AS BANK_NAME,
	BA.Description AS DONOTIMPORT,
	'' AS ROUTING_NUMBER, --NOT IN S300CRE
	BA.Branch AS BRANCH_ID,
	BA.Address_1 AS ADDRESS1,
	BA.Address_2 AS ADDRESS2,
	BA.City AS CITY,
	BA.State AS STATE,
	BA.ZIP AS ZIP,
	'' AS COUNTRY,
	BA.Phone_Number AS PHONE_NUMBER,
	'' AS CURRENCY,
	--BA.General_Cash_Account AS GL_ACCOUNT_OLD, --THIS NEED TRANSLATED
	COALESCE(COALESCE(FFULL.NEW_BASE_ACCOUNT, FNF.NEW_BASE_ACCOUNT),'(MISSING)') AS GL_ACCOUNT,
	'' AS SERVICE_CHARGE_GLACCOUNT, --NOT IN S300CRE
	'' AS INTEREST_EARNED_GLACCOUNT, --NOT IN S300CRE
	TA.NEW_ENTITY_ID AS LOCATION_ID,
	'LGCY_GEN_ACCT:' + BA.General_Cash_Account AS DONOTIMPORT,
	'LAST_RECON:' + COALESCE(FORMAT(BA.Last_Reconciled_Date, 'yyyy-MM-dd'), '') AS DONOTIMPORT

FROM
	[s300].[CMM_MASTER__BANK_ACCOUNT] BA
	LEFT JOIN [MAP].[T_MASTER_ACCOUNT] MA ON BA.General_Cash_Account = MA.ACCOUNT AND BA.Data_Folder_Id = MA.Data_Folder_Id
	LEFT JOIN [MAP].[T_TRANS_ENTITY] TA ON MA.PrefixA = TA.Legacy_Entity_ID AND BA.Data_Folder_Id = TA.DATA_FOLDER_ID --MAY HAVE TO CHANGE THIS
	LEFT JOIN MAP.T_TRANS_BASEACCT AS FFULL --THIS TRIES A FULL ACCOUNT MATCH IF TRANSLATION IS SET TO FULL
		ON FFULL.ACCT_MATCH_TYPE = 'FULL'
		AND FFULL.LEGACY_BASE_ACCOUNT = MA.ACCOUNT
		AND FFULL.Data_Folder_Id = MA.Data_Folder_Id
	LEFT JOIN MAP.T_TRANS_BASEACCT AS FNF --THIS TRIES A PARTIAL ACCOUNT MATCH IF TRANSLATION IS SET TO PARTIAL
		ON FNF.ACCT_MATCH_TYPE = 'BASE'
		--AND FNF.LEGACY_BASE_ACCOUNT = CONCAT(MA.BASEACCOUNT, '.', MA.SUFFIX)
		AND FNF.LEGACY_BASE_ACCOUNT = MA.BASEACCOUNT
		AND FNF.Data_Folder_Id = MA.Data_Folder_Id
		AND FFULL.LEGACY_BASE_ACCOUNT IS NULL
ORDER BY
	BA.Data_Folder_Id,
	BA.Account_Type,
	BA.Bank_Account;
