--MODEL AS OF 02/06/2026
--VENDORS IMPORT
SELECT
	V.Data_Folder_Id AS DONOTIMPORT,
	--LAST_INV_DATE AS DONOTIMPORT, --MISSING THIS FIELD
	--LAST_CHECK_DATE AS DONOTIMPORT, --MISSING THIS FIELD
	--OUTSTNDG_AMOUNT AS DONOTIMPORT, --MISSING THIS FIELD
	TV.NEW_VENDOR_ID AS VENDOR_ID,
	TV.LEGACY_VENDOR_ID AS LEGACY_VENDOR,
	NAME AS NAME,
	TYPE AS VENDTYPE_NAME,
	RECIPIENT_ID AS TAX_ID,
	CUSTOMER_NUMBER AS VENDOR_ACCTNO,
	EXPENSE_ACCOUNT AS GL_ACCTNO,
	0 AS BILLING_TYPE,
	CASE WHEN V.Receives_Form_1099 = 0 THEN '' ELSE TTEN.FORM_TYPE_1099_CODE END AS FORM1099TYPE,
	CASE WHEN V.Receives_Form_1099 = 0 THEN '' ELSE '1' END AS FORM1099BOX,
	RECIPIENT_TAX_ID_NAME AS NAME1099,
	NAME AS CONTACT_NAME,
	NAME AS PRINT_AS,
	TELEPHONE AS PHONE1,
	FAX_NUMBER AS FAX,
	CONTACT_1_EMAIL_ADDRESS AS EMAIL1,
	CONTACT_2_EMAIL_ADDRESS AS EMAIL2,
	'' AS URL1,
	ADDRESS_1 AS ADDRESS1,
	ADDRESS_2 AS ADDRESS2,
	CITY AS CITY,
	TS.STATE_NAME AS STATE,
	ZIP AS ZIP,
	COUNTRY_CODE AS COUNTRY,
	CASE WHEN V.Discount_Days > 0 THEN CAST(V.Discount_Percent AS VARCHAR(10)) + '/' + CAST(V.Discount_Days AS VARCHAR(10)) + ' net ' + CAST(V.Payment_Days AS VARCHAR(10)) WHEN V.Payment_Days = 0 THEN 'Due Upon Receipt' ELSE 'net ' + CAST(V.Payment_Days AS VARCHAR(10)) END AS TERM_NAME,
	CONTACT_1_NAME AS DONOTIMPORT,
	LTRIM(RTRIM(LEFT(V.Contact_1_Name, CHARINDEX(' ', V.Contact_1_Name)))) AS FIRST_NAME,
	SUBSTRING(V.Contact_1_Name, CHARINDEX(' ', V.Contact_1_Name) + 1, 30) AS LAST_NAME,
	CASE WHEN V.Default_Payment_Type = 'Electronic' THEN 'ACH' WHEN V.Default_Payment_Type = 'Check' THEN 'Printed Check' ELSE 'Unknown Type' END AS PAYMENT_METHOD,
	CASE WHEN V.Default_Payment_Type = 'Electronic' THEN 'T' WHEN V.Default_Payment_Type = 'Check' THEN 'F' ELSE 'Unknown Type' END AS ACH_ENABLED,
	RIGHT('000000000' + CAST(V.Bank_ID AS VARCHAR(20)), 9) AS ACH_BANK_ROUTING_NUMBER,
	BANK_ACCOUNT AS ACH_ACCOUNT_NUMBER,
	CASE WHEN V.Account_Type = 'Checking' THEN 'Checking Account' ELSE 'Savings Account' END AS ACH_ACCOUNT_TYPE,
	CASE WHEN V.Default_Payment_Type = 'Electronic' THEN 'CCD' END AS ACH_SEC_CODE,
	CASE WHEN V.Default_Payment_Type = 'Electronic' THEN 'T' ELSE 'F' END AS PAYMENT_NOTIFICATION,
	VENDOR AS DONOTIMPORT,
	NAME AS DONOTIMPORT,
	ACCOUNT_TYPE AS DONOTIMPORT
FROM
	[s300].[APM_MASTER__VENDOR] V
	LEFT JOIN [MAP].[T_TRANS_VENDOR] TV ON V.Vendor = TV.LEGACY_VENDOR_ID AND V.Data_Folder_Id = TV.Data_Folder_Id
	--LEFT JOIN [MAP].[T_TRANS_VENDOR] TV ON V.Vendor = TV.LEGACY_VENDOR_ID
	LEFT JOIN [MAP].[T_1099_TYPE] TTEN ON V.Form_Type_1099 = TTEN.FORM_TYPE_1099_DESC
	LEFT JOIN [MAP].[T_STATE] TS ON V.State = TS.STATE_ID
WHERE
	TV.INCLUDE_VENDOR = '1';
