--MODEL AS OF 02/06/2026
--CUSTOMERS IMPORT
SELECT
	C.DATA_FOLDER_ID AS DONOTIMPORT,
	TC.NEW_CUSTOMER_ID AS CUSTOMER_ID,
	C.CUSTOMER AS LEGACY_CUSTOMER,
	C.NAME AS CUST_NAME,
	--CASE WHEN C.Material_Exempt_Status = 'Taxable' THEN 'T' ELSE 'F' END AS TAXABLE, --Missing MATERIAL_EXEMPT_STATUS FIELD
	C.TAX_GROUP AS TAXGROUP,
	CASE WHEN C.Days_Before_Due = 0 THEN '' ELSE 'Net ' + FORMAT(C.Days_Before_Due, '#') END AS TERM_NAME,
	C.CREDIT_LIMIT AS CREDIT_LIMIT,
	'' AS ACTIVE,
	C.NAME AS CONTACT_NAME,
	C.NAME AS PRINT_AS,
	C.TELEPHONE AS PHONE1,
	C.FAX AS FAX,
	C.Email_Address AS EMAIL1,
	C.ADDRESS_1 AS ADDRESS1,
	C.ADDRESS_2 AS ADDRESS2,
	C.CITY AS CITY,
	TS1.STATE_NAME AS STATE,
	C.ZIP_CODE AS ZIP,
	'' AS COUNTRY,
	C.Billing_Contact AS B_CONTACT_NAME,
	C.Billing_Email_Address AS B_EMAIL1,
	C.Billing_Address_1 AS B_ADDRESS1,
	C.Billing_Address_2 AS B_ADDRESS2,
	C.Billing_City AS B_CITY,
	TS2.STATE_NAME AS B_STATE,
	C.Billing_ZIP_Code AS B_ZIP
FROM
	[s300].[ARM_MASTER__CUSTOMER] C
	LEFT JOIN [MAP].[T_TRANS_CUSTOMER] TC ON C.CUSTOMER = TC.LEGACY_CUSTOMER_ID AND C.Data_Folder_Id = TC.Data_Folder_Id
	LEFT JOIN [MAP].[T_STATE] TS1 ON C.State = TS1.STATE_ID
	LEFT JOIN [MAP].[T_STATE] TS2 ON C.Billing_State = TS2.STATE_ID
WHERE
	TC.INCLUDE_CUSTOMER = '1';
