--MODEL AS OF 02/09/2026
--STANDARD COST TYPES
SELECT
	CT.Data_Folder_Id AS DONOTIMPORT,
	'LGCY_CT|' + CT.Category AS DONOTIMPORT,
	'LGCY_ACCT|' + CT.Cost_Account_A AS DONOTIMPORT,
	TCT.NEW_COST_TYPE_ID AS STANDARDCOSTTYPE_ID,
	CT.Description AS STANDARDCOSTTYPE_NAME,
	'' AS DESCRIPTION,
	CT.Accumulate_As AS ACCUMULATIONTYPENAME,
	CT.Cost_Unit_Description AS COSTUNITDESCRIPTION,
	'T' AS ACTIVE,
	COALESCE(TBA.New_Base_Account, '') AS ACCOUNTNO,
	'' AS PARENT_STANDARDCOSTTYPE,
	CT.Accumulate_As AS ITEM_ID,
	CT.Category AS LEGACY_ID
FROM
	[s300].[JCM_MASTER__STANDARD_CATEGORY] CT
	LEFT JOIN [MAP].[T_TRANS_COST_TYPE] TCT ON CT.Category = TCT.LEGACY_COST_TYPE_ID AND CT.Data_Folder_Id = TCT.DATA_FOLDER_ID
	LEFT JOIN [MAP].[T_TRANS_BASEACCT] TBA ON CT.Cost_Account_A = TBA.LEGACY_BASE_ACCOUNT AND CT.Data_Folder_Id = TBA.Data_Folder_Id
ORDER BY
	CT.Data_Folder_Id,
	CT.Category;
