--MODEL AS OF 05/06/2026
--PROJECTS IMPORT
SELECT
	J.Data_Folder_Id AS DONOTIMPORT,
	TJ.NEW_JOB_ID AS PROJECT_ID,
	J.Description AS PROJECT_NAME,
	J.Job AS LEGACY_PROJECT_ID,
	--J.|Contract AS PROJECT_CATEGORY,--MISSING
	'Contract' AS PROJECT_CATEGORY, --MAY NEED CHANGED
	--J.#GET - Intacct Department From Mapping AS DEPARTMENT_ID,
	'' AS PRINT_AS,
	J.Address_1 AS STREET_ADDRESS_LINE_1,
	J.Address_2 AS STREET_ADDRESS_LINE_2,
	J.City AS CITY,
	J.State AS STATE,
	J.ZIP_Code AS ZIP,
	--J.|Misc_Title_2 AS CONTRACTOR,--MISSING
	--J.#GET - Intacct Job Parent From Mapping AS PARENT_PROJECT_ID,
	'Fixed Fee' AS BILLINGTYPE,
	'Active' AS PROJECT_STATUS,
	TC.NEW_CUSTOMER_ID AS CUSTOMER_ID,
	--J.|Project_Manager AS PROJECT_MANAGER_ID,--MISSING
	--J.|ACTIVE AS STATUS,--MISSING
	COALESCE(FORMAT(J.Actual_Start_Date, 'yyyy-MM-dd'), '') AS BEGIN_DATE,
	COALESCE(FORMAT(J.Estimated_Comp_Date, 'yyyy-MM-dd'), '') AS END_DATE,
	TE.NEW_ENTITY_ID AS LOCATION_ID,
	TD.NEW_DEPARTMENT_ID AS DEPARTMENT_ID,
	'' AS CLASS_ID,
	--J.|Scope_of_Work AS DONOTIMPORT,--MISSING
	J.AR_Customer AS DONOTIMPORT,
	J.Cost_Account_Prefix AS DONOTIMPORT,
	COALESCE(FORMAT(J.Last_Cost_Update, 'yyyy-MM-dd'), '') AS DONOTIMPORT,
	J.Billing_Method AS DONOTIMPORT
FROM
	[s300].[JCM_MASTER__JOB] J
	LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON J.Job = TJ.LEGACY_JOB_ID AND J.Data_Folder_Id = TJ.Data_Folder_Id
	LEFT JOIN [MAP].[T_TRANS_CUSTOMER] TC ON J.AR_Customer = TC.LEGACY_CUSTOMER_ID and J.Data_Folder_Id = TC.DATA_FOLDER_ID
	LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON J.Data_Folder_Id = TE.Data_Folder_Id
	LEFT JOIN [MAP].[T_TRANS_DEPARTMENT] TD ON J.Cost_Account_Prefix = TD.Legacy_Department_ID and J.Data_Folder_Id = TD.Data_Folder_ID
WHERE
	TJ.INCLUDE_JOB = '1';
