--MODEL AS OF 02/09/2026
--VENDOR 1099 Opening Balances
SELECT
	MV.Data_Folder_Id AS DONOTIMPORT,
	TV.NEW_VENDOR_ID AS VENDORID,
	MV.Name AS VENDORNAME,
	TE.NEW_ENTITY_ID AS ENTITY,
	COALESCE(TNN.FORM_TYPE_1099_CODE, '') AS FORM1099TYPE,
	'1' AS FORM1099BOX,
	--MV.Amt_Paid_This_Yr_1099 AS AMOUNT, --MISSING Amt_Paid_This_Yr_1099
	MV.Form_Type_1099 AS DONOTIMPORT,
	MV.Receives_Form_1099 AS DONOTIMPORT,
	'LG_VD|' + MV.Vendor AS DONOTIMPORT
FROM
	[s300].[APM_MASTER__VENDOR] MV
	LEFT JOIN [MAP].[T_TRANS_VENDOR] TV ON MV.Vendor = TV.LEGACY_VENDOR_ID AND MV.Data_Folder_Id = TV.Data_Folder_Id
	LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON MV.Data_Folder_Id = TE.Data_Folder_ID
	LEFT JOIN [MAP].[T_1099_TYPE] TNN ON MV.Form_Type_1099 = TNN.FORM_TYPE_1099_DESC --NO DATA FOLDER CONNECTION NEEDED
WHERE
	MV.Receives_Form_1099 = '1'
	AND TV.INCLUDE_VENDOR = '1'
	--	AND MV.Amt_Paid_This_Yr_1099 > 0.00; --MISSING Amt_Paid_This_Yr_1099