--MODEL AS OF 02/09/2026
--STANDARD COST CODES
SELECT
	CC.Data_Folder_Id AS DONOTIMPORT,
	'LGCY_CC|' + CC.Cost_Code AS DONOTIMPORT,
	TCC.NEW_COST_CODE_ID AS STANDARDTASK_ID,
	TCC.NEW_COST_CODE_NAME AS STANDARDTASK_NAME,
	'' AS DESCRIPTION,
	'T' AS ACTIVE,
	TCC.NEW_ITEM_ID AS ITEM_ID,
	'T' AS BILLABLE,
	'' AS MILESTONE,
	'' AS UTILIZED,
	'' AS PRIORITY,
	'' AS TIMETYPE_NAME,
	'' AS WBS_CODE,
	'' AS PARENT_STANDARDTASK_ID,
	'' AS CLASS_ID,
	'' AS PRODUCTIONUNITDESC
	--CC.| AS STANDARDCOSTTYPES_STANDARDCOSTTYPEID--MISSING Pulls in Categories 1 - 12?
FROM
	[s300].[JCM_MASTER__COST_CODE] CC
	LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON CC.Cost_Code = TCC.LEGACY_COST_CODE_ID AND CC.Data_Folder_Id = TCC.Data_Folder_Id
ORDER BY
	CC.Data_Folder_Id,
	CC.Cost_Code;
