--MODEL AS OF 05/07/2026
--STANDARD COST CODES --WORKING ON THIS
SELECT
	C.DONOTIMPORT1 AS DONOTIMPORT,
	C.DONOTIMPORT2 AS DONOTIMPORT,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY C.STANDARDTASK_ID ORDER BY C.DONOTIMPORT1, C.STANDARDTASK_ID)) = 1 THEN C.STANDARDTASK_ID ELSE '' END AS STANDARDTASK_ID,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY C.STANDARDTASK_ID ORDER BY C.DONOTIMPORT1, C.STANDARDTASK_ID)) = 1 THEN C.STANDARDTASK_NAME ELSE '' END AS STANDARDTASK_NAME,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY C.STANDARDTASK_ID ORDER BY C.DONOTIMPORT1, C.STANDARDTASK_ID)) = 1 THEN C.DESCRIPTION ELSE '' END AS DESCRIPTION,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY C.STANDARDTASK_ID ORDER BY C.DONOTIMPORT1, C.STANDARDTASK_ID)) = 1 THEN C.ACTIVE ELSE '' END AS ACTIVE,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY C.STANDARDTASK_ID ORDER BY C.DONOTIMPORT1, C.STANDARDTASK_ID)) = 1 THEN C.ITEM_ID ELSE '' END AS ITEM_ID,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY C.STANDARDTASK_ID ORDER BY C.DONOTIMPORT1, C.STANDARDTASK_ID)) = 1 THEN C.BILLABLE ELSE '' END AS BILLABLE,
	C.MILESTONE,
	C.UTILIZED,
	C.PRIORITY,
	C.TIMETYPE_NAME,
	C.WBS_CODE,
	C.PARENT_STANDARDTASK_ID,
	C.CLASS_ID,
	C.PRODUCTIONUNITDESC,
	C.STANDARDCOSTTYPES_STANDARDCOSTTYPEID
FROM(
	SELECT DISTINCT
		SCC.Data_Folder_Id AS DONOTIMPORT1,
		'LGCY_CC | ' + SCC.Cost_Code AS DONOTIMPORT2,
		TCC.NEW_COST_CODE_ID AS STANDARDTASK_ID,
		SCC.Description AS STANDARDTASK_NAME,
		'' AS DESCRIPTION,
		'T' AS ACTIVE,
		'T' AS ITEM_ID,
		'T' AS BILLABLE,
		'' AS MILESTONE,
		'' AS UTILIZED,
		'' AS PRIORITY,
		'' AS TIMETYPE_NAME,
		'' AS WBS_CODE,
		CASE
			WHEN (CAST(CASE WHEN CHARINDEX('-', SCC.Cost_Code) > 0 THEN RIGHT(SCC.Cost_Code, LEN(SCC.Cost_Code) - CHARINDEX('-', SCC.Cost_Code)) END AS INT)) = 0
				THEN ''
			ELSE
				(CASE WHEN CHARINDEX('-', SCC.Cost_Code) > 0 THEN LEFT(SCC.Cost_Code, CHARINDEX('-', SCC.Cost_Code) - 1) END)
				+ '-' +
				(REPLICATE('0', LEN(CASE WHEN CHARINDEX('-', SCC.Cost_Code) > 0 THEN RIGHT(SCC.Cost_Code, LEN(SCC.Cost_Code) - CHARINDEX('-', SCC.Cost_Code)) END)))
		END AS PARENT_STANDARDTASK_ID,
		'' AS CLASS_ID,
		'' AS PRODUCTIONUNITDESC,
		CA.CategoryValue AS STANDARDCOSTTYPES_STANDARDCOSTTYPEID
	FROM 
		[s300].[JCM_MASTER__STANDARD_COST_CODE] SCC
		CROSS APPLY (VALUES
			(SCC.Category_1),
			(SCC.Category_2),
			(SCC.Category_3),
			(SCC.Category_4),
			(SCC.Category_5),
			(SCC.Category_6),
			(SCC.Category_7),
			(SCC.Category_8),
			(SCC.Category_9),
			(SCC.Category_10),
			(SCC.Category_11),
			(SCC.Category_12)
		) CA(CategoryValue)
		LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON SCC.Cost_Code = TCC.LEGACY_COST_CODE_ID AND SCC.Data_Folder_Id = TCC.Data_Folder_Id
	WHERE 
		(LTRIM(RTRIM(CA.CategoryValue)) <> '' AND CAST(RIGHT(SCC.Cost_Code, LEN(SCC.Cost_Code) - CHARINDEX('-', SCC.Cost_Code)) AS INT) != 0)
		OR(LTRIM(RTRIM(CA.CategoryValue)) = '' AND CAST(RIGHT(SCC.Cost_Code, LEN(SCC.Cost_Code) - CHARINDEX('-', SCC.Cost_Code)) AS INT) = 0)
		) C
ORDER BY
	C.DONOTIMPORT1,
	C.STANDARDTASK_ID;