--AS OF 03/11/2026
--PROJECT CONTRACT HEADER
SELECT DISTINCT
	ACI.Data_Folder_Id AS DONOTIMPORT,
	AC.Contract AS DONOTIMPORT,
	CASE WHEN CHARINDEX('-', AC.Contract) * CHARINDEX('-', TJ.NEW_JOB_ID) > 0
		THEN LEFT(TJ.NEW_JOB_ID, CHARINDEX('-', TJ.NEW_JOB_ID) - 1) + SUBSTRING(AC.Contract, CHARINDEX('-', AC.Contract), LEN(AC.Contract))
		ELSE AC.Contract END AS PROJECTCONTRACTID,
	AC.Description AS NAME,
	TJ.NEW_JOB_ID AS PROJECTID,
	TC.NEW_CUSTOMER_ID AS CUSTOMERID,
	CAST(COALESCE(AC.Contract_Date, AC.DATE_STAMP) AS DATE) AS DATE,
	'' AS DESCRIPTION,
	--ACI.#PROJECTCONTRACTTYPE AS PROJECTCONTRACTTYPE,
	CASE WHEN ACI.Billing_Type in('Progress Billing','Lump Sum') THEN 'Fixed Price' ELSE 'TM' END AS PROJECTCONTRACTTYPE,
	'' AS ARCHITECT,
	'true' AS BILLABLE,
	'active' AS STATUS,
	--ACI.#Max of CNC_ACTIVE_CONTRACT_ITEM.Job AS DONOTIMPORT,
	--ACI.#Max of CNC_ACTIVE_CONTRACT_ITEM.Customer AS DONOTIMPORT,
	'true' AS POSTED,
	CAST(COALESCE(AC.Contract_Date, AC.DATE_STAMP) AS DATE) AS POSTEDTO,
	'Original Contract' AS ORIGINALGLBUDGETID,
	'Revision Contract' AS REVISIONGLBUDGETID,
	'Approved CO Contract' AS APPROVEDGLBUDGETID,
	'Pending CO Contract' AS PENDINGGLBUDGETID,
	'Forecast Contract' AS FORECASTGLBUDGETID,
	'Other Contract' AS OTHERGLBUDGETID,
	ACD.Revised_Contract AS DONOTIMPORT,
	ACD.Total_Billed AS DONOTIMPORT,
	ACD.Cash_Receipt AS DONOTIMPORT,
	ACD.Receivable_Adjustment AS DONOTIMPORT,
	ACD.Retainage_Held AS DONOTIMPORT,
	ACD.Retainage_Billed AS DONOTIMPORT
FROM
	[s300].[CNC_ACTIVE__CONTRACT_ITEM] ACI
	LEFT JOIN [s300].[ARM_MASTER__CUSTOMER] C ON ACI.Data_Folder_Id = C.Data_Folder_Id and ACI.Customer = C.Customer
	LEFT JOIN [s300].[CNC_ACTIVE__CONTRACT] AC ON ACI.Data_Folder_Id = AC.Data_Folder_Id AND ACI.Contract = AC.Contract
	LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_ITEM_DERIVED] ACID ON ACI.Data_Folder_Id = ACID.Data_Folder_ID AND ACI.Contract = ACID.Contract AND ACI.Contract_Item = ACID.Contract_Item
	LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_DERIVED] ACD ON AC.Data_Folder_Id = ACD.Data_Folder_Id AND AC.Contract = ACD.Contract
	LEFT JOIN [s300].[JCM_MASTER__JOB] J ON ACI.Data_Folder_Id = J.Data_Folder_Id AND ACI.Job = J.Job
	--LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON AC.Data_Folder_Id = TJ.DATA_FOLDER_ID AND AC.Contract = TJ.LEGACY_JOB_ID
	LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON ACI.Data_Folder_Id = TJ.DATA_FOLDER_ID AND ACI.JOB = TJ.LEGACY_JOB_ID
	LEFT JOIN [MAP].[T_TRANS_CUSTOMER] TC ON ACI.Data_Folder_Id = TC.DATA_FOLDER_ID AND ACI.Customer = TC.LEGACY_CUSTOMER_ID
WHERE
	TJ.INCLUDE_JOB = 1;
