--MODEL AS OF 05/13/2026
--COST TYPES IMPORT
SELECT
	C.Data_Folder_Id AS DONOTIMPORT,
	TJ.NEW_JOB_ID AS PROJECT_ID,
	COALESCE(TCC.NEW_COST_CODE_ID, C.COST_CODE) AS TASK_ID, --COST CODE
	TCT.NEW_COST_TYPE_ID AS STANDARDCOSTTYPE_ID, --COST TYPE
	'L_JOB | ' + C.Job AS DONOTIMPORT,
	'L_EXTRA | ' + C.Extra AS DONOTIMPORT,
	'L_CC | ' + C.Cost_Code AS DONOTIMPORT,
	'L_CT | ' + C.Category AS DONOTIMPORT
FROM
	[s300].[JCM_MASTER__CATEGORY] C
	LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON C.JOB = TJ.LEGACY_JOB_ID AND C.Data_Folder_Id = TJ.DATA_FOLDER_ID
	LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON C.COST_CODE = TCC.LEGACY_COST_CODE_ID AND C.Data_Folder_Id = TCC.DATA_FOLDER_ID
	LEFT JOIN [MAP].[T_TRANS_COST_TYPE] TCT ON C.CATEGORY = TCT.LEGACY_COST_TYPE_ID AND C.Data_Folder_Id = TCT.DATA_FOLDER_ID
WHERE
	TJ.INCLUDE_JOB = '1';