--MODEL AS OF 04/07/2026 - Changed to omit zero balance lines
--OPEN AP IMPORT
SELECT
	B.DONOTIMPORT12 AS DONOTIMPORT,
	B.DONOTIMPORT01 DONOTIMPORT,
	CASE WHEN B.LINE = 1 THEN B.TRANSACTIONTYPE ELSE '' END AS TRANSACTIONTYPE,
	CASE WHEN B.LINE = 1 THEN B.DATE ELSE '' END AS DATE,
	CASE WHEN B.LINE = 1 THEN B.GLPOSTINGDATE ELSE '' END AS GLPOSTINGDATE,
	CASE WHEN B.LINE = 1 THEN B.VENDOR_ID ELSE '' END AS VENDOR_ID,
	CASE WHEN B.LINE = 1 THEN B.VENDORDNOCNO ELSE '' END AS VENDORDNOCNO,
	CASE WHEN B.LINE = 1 THEN B.DOCUMENTNO ELSE '' END AS DOCUMENTNO,
	CASE WHEN B.LINE = 1 THEN B.REFERENCENO ELSE '' END AS REFERENCENO,
	CASE WHEN B.LINE = 1 THEN B.DATEDUE ELSE '' END AS DATEDUE,
	CASE WHEN B.LINE = 1 THEN B.PROJECTID ELSE '' END AS PROJECTID,
	CASE WHEN B.LINE = 1 THEN B.STATE ELSE '' END AS STATE,
	B.LINE,
	B.ITEMID,
	B.ITEMDESC,
	B.QUANTITY,
	B.UNIT,
	B.CONVERSIONTYPE,
	B.PRICE,
	B.LOCATIONID AS LOCATIONID,
	B.DEPARTMENTID,
	B.PODOCUMENTENTRY_PROJECTID,
	B.PODOCUMENTENTRY_TRX_AMOUNTRETAINED,
	B.PODOCUMENTENTRY_TASKID,
	B.PODOCUMENTENTRY_COSTTYPEID,
	B.PODOCUMENTENTRY_VENDORID,
	B.MEMO,
	B.DONOTIMPORT02 AS DONOTIMPORT,
	B.DONOTIMPORT03 AS DONOTIMPORT,
	B.DONOTIMPORT04 AS DONOTIMPORT,
	B.DONOTIMPORT05 AS DONOTIMPORT,
	B.DONOTIMPORT06 AS DONOTIMPORT,
	B.DONOTIMPORT07 AS DONOTIMPORT,
	B.DONOTIMPORT08 AS DONOTIMPORT,
	B.DONOTIMPORT09 AS DONOTIMPORT,
	B.DONOTIMPORT10 AS DONOTIMPORT,
	B.DONOTIMPORT11 AS DONOTIMPORT,
	B.DONOTIMPORT13 AS DONOTIMPORT
FROM
	(SELECT
		CASE WHEN ((TE.PKG_NPC_COMMIT = 0) OR (TE.PKG_NPC_COMMIT = 1 AND (APMD.Job = '' OR TJ.INCLUDE_JOB = 0))) THEN '' ELSE '#NPC' END AS DONOTIMPORT12,
		APB.Data_Folder_Id AS DONOTIMPORT01,
		'Startup AP' AS TRANSACTIONTYPE,
		COALESCE(FORMAT(APB.Invoice_Date, 'yyyy-MM-dd'), '') AS DATE,
		COALESCE(FORMAT(APB.Accounting_Date, 'yyyy-MM-dd'), '') AS GLPOSTINGDATE,
		TV.NEW_VENDOR_ID AS VENDOR_ID,
		APB.Invoice AS VENDORDNOCNO,
		APB.Invoice AS DOCUMENTNO,
		APB.Invoice AS REFERENCENO,
		COALESCE(FORMAT(APB.Payment_Date, 'yyyy-MM-dd'), '') AS DATEDUE,
		--COALESCE(TJ.NEW_JOB_ID,'') AS PROJECTID,
		COALESCE(CASE WHEN TJ.INCLUDE_JOB = 1 THEN TJ.NEW_JOB_ID ELSE '' END, '') AS PROJECTID,
		'Closed' AS STATE,
		ROW_NUMBER() OVER (PARTITION BY APMD.Data_Folder_Id, APMD.Vendor, APMD.Invoice ORDER BY APMD.Data_Folder_Id, APMD.Vendor, APMD.Invoice, APMD.Dist_Seq) AS LINE,
		'Beginning Balance' AS ITEMID,
		APMD.Description AS ITEMDESC,
		'1' AS QUANTITY,
		'Each' AS UNIT,
		'Price' AS CONVERSIONTYPE,
		APMD.Amount-APMD.Amount_Paid AS PRICE,
		TE.NEW_ENTITY_ID AS LOCATIONID,
		'' AS DEPARTMENTID,
		--COALESCE(TJ.NEW_JOB_ID, '') AS PODOCUMENTENTRY_PROJECTID,
		COALESCE(CASE WHEN TJ.INCLUDE_JOB = 1 THEN TJ.NEW_JOB_ID ELSE '' END, '') AS PODOCUMENTENTRY_PROJECTID,
		APMD.Retainage - APMD.Retainage_Paid AS PODOCUMENTENTRY_TRX_AMOUNTRETAINED,
		COALESCE(TCC.NEW_COST_CODE_ID, '') AS PODOCUMENTENTRY_TASKID,
		COALESCE(TCT.NEW_COST_TYPE_ID, '') AS PODOCUMENTENTRY_COSTTYPEID,
		TV.NEW_VENDOR_ID AS PODOCUMENTENTRY_VENDORID,
		APMD.Description AS MEMO,
		APMD.Amount-APMD.Amount_Paid AS DONOTIMPORT02,
		'LG_VEND_ID|' + APB.Vendor AS DONOTIMPORT03,
		'LG_VEND_NAME|' + APV.Name AS DONOTIMPORT04,
		'LG_JOB|' + APMD.Job AS DONOTIMPORT05,
		'LG_EXTRA|' + APMD.Extra AS DONOTIMPORT06,
		'GL_PREF|' + LEFT(APMD.Expense_Account, GLF.Account_Prefix_A_Length) AS DONOTIMPORT07,
		'LG_CC|' + APMD.Cost_Code AS DONOTIMPORT08,
		'LG_DESC|' + APMD.Description AS DONOTIMPORT09,
		'LG_CT|' + APMD.Category AS DONOTIMPORT10,
		'LG_COMMIT|' + APMD.Commitment AS DONOTIMPORT11,
		'VND_CHK|' + CASE WHEN TV.INCLUDE_VENDOR = 1 THEN 'ok' ELSE 'Missing Vendor' END AS DONOTIMPORT13
	FROM
		[s300].[APM_MASTER__DISTRIBUTION] APMD
		LEFT JOIN [s300].[APM_MASTER__INVOICE] APB ON APMD.Data_Folder_Id = APB.Data_Folder_Id AND APB.Vendor = APMD.Vendor and APB.Invoice = APMD.Invoice
		LEFT JOIN [s300].[APM_MASTER__VENDOR] APV ON APMD.Vendor = APV.Vendor AND APMD.Data_Folder_Id = APV.Data_Folder_Id
		LEFT JOIN [MAP].[T_TRANS_VENDOR] TV ON APMD.Vendor = TV.LEGACY_VENDOR_ID AND APMD.Data_Folder_Id = TV.Data_Folder_id
		LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON APMD.Cost_Code = TCC.LEGACY_COST_CODE_ID AND APMD.Data_Folder_Id = TCC.Data_Folder_Id
		LEFT JOIN [MAP].[T_TRANS_COST_TYPE] TCT ON APMD.Category = TCT.LEGACY_COST_TYPE_ID AND APMD.Data_Folder_Id = TCT.Data_Folder_ID
		LEFT JOIN [s300].[GLM_MASTER__ACCOUNT_FORMAT] GLF ON APMD.Data_Folder_Id = GLF.Data_Folder_Id
		LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON APMD.Job = TJ.LEGACY_JOB_ID AND APMD.Data_Folder_Id = TJ.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON APMD.Data_Folder_Id = TE.DATA_FOLDER_ID
	WHERE
		APB.Status = 'Open'
		AND (APMD.Amount-APMD.Amount_Paid) != 0 OR (APMD.Retainage - APMD.Retainage_Paid) != 0) B
ORDER BY
	B.DONOTIMPORT01,
	B.VENDOR_ID,
	B.VENDORDNOCNO,
	B.LINE;
