--MODEL AS OF 02/06/2026
--COST CODES IMPORT
SELECT
	CC.Data_Folder_Id AS DONOTIMPORT,
	TCC.NEW_COST_CODE_NAME AS TASK_NAME,
	TJ.NEW_JOB_ID AS PROJECT_ID,
	TCC.NEW_ITEM_ID AS ITEM_ID,
	'T' AS BILLABLE,
	'T' AS ACTIVE,
	TCC.NEW_COST_CODE_ID AS STANDARDTASK_ID,
	'' AS COSTTYPE_ID,
	TCC.NEW_COST_CODE_ID AS TASK_ID, --COST CODE
	'' AS DONOTIMPORT,
	'' AS DONOTIMPORT,
	'' AS DONOTIMPORT,
	'' AS DONOTIMPORT
FROM
	[s300].[JCM_MASTER__COST_CODE] CC
	LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON CC.JOB = TJ.LEGACY_JOB_ID AND CC.Data_Folder_Id = TJ.DATA_FOLDER_ID
	LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON CC.COST_CODE = TCC.LEGACY_COST_CODE_ID AND CC.Data_Folder_Id = TCC.DATA_FOLDER_ID
WHERE
	TJ.INCLUDE_JOB = '1';
