--MODEL AS OF 05/13/2026
--COST CODES IMPORT
SELECT
	CC.Data_Folder_Id AS DONOTIMPORT,
	CASE WHEN TCC.NEW_COST_CODE_NAME IS NULL THEN CC.Description ELSE TCC.NEW_COST_CODE_NAME END AS TASK_NAME,
	TJ.NEW_JOB_ID AS PROJECT_ID,
	--COALESCE(TCC.NEW_ITEM_ID, 'Other') AS ITEM_ID,
	'Other' AS ITEM_ID,
	'T' AS BILLABLE,
	'T' AS ACTIVE,
	COALESCE(TCC.NEW_COST_CODE_ID, '') AS STANDARDTASK_ID,
	'' AS COSTTYPE_ID,
	CASE WHEN COALESCE(TCC.NEW_COST_CODE_ID, '') = '' THEN COALESCE(TCC.NEW_COST_CODE_ID, CC.COST_CODE) ELSE '' END AS TASK_ID,--COST CODE
	'LGCY_CC | ' + CC.Cost_Code AS DONOTIMPORT,
	'' AS DONOTIMPORT,
	'' AS DONOTIMPORT,
	'' AS DONOTIMPORT
FROM
	[s300].[JCM_MASTER__COST_CODE] CC
	LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON CC.JOB = TJ.LEGACY_JOB_ID AND CC.Data_Folder_Id = TJ.DATA_FOLDER_ID
	LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON CC.COST_CODE = TCC.LEGACY_COST_CODE_ID AND CC.Data_Folder_Id = TCC.DATA_FOLDER_ID
WHERE
	TJ.INCLUDE_JOB = '1';