--AS OF 03/09/2026 (This might be the same as the 03/04/2026 version)
--PROJECT CONTRACT LINES USING ACTIVE CONTRACT ITEM
SELECT
	--B.ENTRY_WFTYPE AS DONOTIMPORT_TEMP,
	--B.LEGACY_CONTRACT,
	B.DONOTIMPORT1 AS DONOTIMPORT,
	--ACL.Contract AS PROJECTCONTRACTID,
	B.PROJECTCONTRACTID,
	B.PROJECTCONTRACTLINEID,
	B.NAME,
	B.PROJECTID,
	B.ITEMID,
	B.DESCRIPTION,
	B.CONTRACTLINEDATE,
	B.GLACCOUNTID,
	B.RETAINAGEPERCENTAGE,
	B.BILLABLE,
	B.STATUS,
	B.BILLINGTYPE,
	B.MAXIMUMBILLING,
	B.MAXIMUMBILLINGAMOUNT,
	B.DEFAULTRATETABLEID,
	B.TSRATETABLEID,
	B.PORATETABLEID,
	B.APRATETABLEID,
	B.GLRATETABLEID,
	B.CCRATETABLEID,
	B.DEPARTMENTID,
	B.ENTRY_WFTYPE,
	B.ENTRY_PROJECTID,
	B.ENTRY_TASKID,
	B.ENTRY_COSTTYPEID,
	B.ENTRY_ITEMID,
	B.ENTRY_PRICE,
	B.ENTRY_PRICEEFFECTIVEDATE,
	B.ENTRY_MEMO,
	B.ENTRY_DEPARTMENTID,
	B.TASKID,
	B.COSTTYPEID,
	B.ENTRY_CUSTOMERID,
	B.DONOTIMPORT2 AS DONOTIMPORT,
	B.DONOTIMPORT3 AS DONOTIMPORT,
	B.DONOTIMPORT4 AS DONOTIMPORT,
	B.DONOTIMPORT5 AS DONOTIMPORT,
	B.DONOTIMPORT6 AS DONOTIMPORT,
	B.DONOTIMPORT7 AS DONOTIMPORT,
	B.DONOTIMPORT8 AS DONOTIMPORT,
	B.DONOTIMPORT9 AS DONOTIMPORT,
	B.DONOTIMPORT10 AS DONOTIMPORT,
	B.DONOTIMPORT11 AS DONOTIMPORT,
	B.DONOTIMPORT12 AS DONOTIMPORT,
	B.DONOTIMPORT13 AS DONOTIMPORT
FROM
	(SELECT --ORIGINAL
		ACL.Data_Folder_Id AS DONOTIMPORT1,
		--ACL.Contract AS PROJECTCONTRACTID,
		--TJ.NEW_JOB_ID AS PROJECTCONTRACTID,
		CASE WHEN CHARINDEX('-', AC.Contract) * CHARINDEX('-', TJ.NEW_JOB_ID) > 0
		  THEN LEFT(TJ.NEW_JOB_ID, CHARINDEX('-', TJ.NEW_JOB_ID) - 1) + SUBSTRING(AC.Contract, CHARINDEX('-', AC.Contract), LEN(AC.Contract))
		  ELSE AC.Contract END AS PROJECTCONTRACTID,
		ACL.Contract_Item AS PROJECTCONTRACTLINEID,
		ACL.Description AS NAME,
		TJ.NEW_JOB_ID AS PROJECTID,
		'' AS ITEMID,
		ACL.Description AS DESCRIPTION,
		COALESCE(CAST(ACL.Approval_Date AS DATE),CAST(ACL.Date_Stamp AS DATE)) AS CONTRACTLINEDATE,
		ACL.Default_Revenue_Account AS GLACCOUNTID,
		ACL.Retainage_Percent AS RETAINAGEPERCENTAGE,
		'true' AS BILLABLE,
		'active' AS STATUS,
		CASE WHEN ACL.Billing_Type IS NULL THEN ''
			 WHEN ACL.Billing_Type IN ('Progress Billing', 'Lump Sum') THEN 'Progress'
			 ELSE 'TM' END AS BILLINGTYPE,
		CASE WHEN ACL.Billing_Type = 'Cost Plus to Maximum' THEN 'Specified amount'
			 WHEN ACL.Billing_Type = 'Time & Materials' THEN 'No maximum'
			 ELSE '' END AS MAXIMUMBILLING,
		COALESCE(CASE WHEN ACL.Billing_Type = 'Cost Plus to Maximum'
				 THEN ACLD.Revised_Contract
				 WHEN ACL.Billing_Type = 'Time & Materials'
				 THEN 0 ELSE NULL END, 0) AS MAXIMUMBILLINGAMOUNT,
		ACL.Markup_Table AS DEFAULTRATETABLEID,
		ACL.Rate_Table_Labor AS TSRATETABLEID,
		ACL.Rate_Table_Subcontract AS PORATETABLEID,
		ACL.Rate_Table_Material AS APRATETABLEID,
		ACL.Rate_Table_Equipment AS GLRATETABLEID,
		ACL.Rate_Table_Other AS CCRATETABLEID,
		'' AS DEPARTMENTID,
		CASE WHEN ACL.Original_Contract_Total >= 0 THEN 'original'
			ELSE '' END AS ENTRY_WFTYPE,
		TJ.NEW_JOB_ID AS ENTRY_PROJECTID,
		'' AS ENTRY_TASKID,
		'' AS ENTRY_COSTTYPEID,
		'Contract Item' AS ENTRY_ITEMID,
		ACL.Original_Contract_Total AS ENTRY_PRICE,
		CAST(COALESCE(ACL.Approval_Date, ACL.Date_Stamp) AS DATE) AS ENTRY_PRICEEFFECTIVEDATE,
		'' AS ENTRY_MEMO,
		'' AS ENTRY_DEPARTMENTID,
		'' AS TASKID,
		'' AS COSTTYPEID,
		TC.NEW_CUSTOMER_ID AS ENTRY_CUSTOMERID,
		'LG_PROJECT|' + ACL.Job AS DONOTIMPORT2,
		'LG_CUST|' + ACL.Customer AS DONOTIMPORT3,
		ACLD.Revised_Contract AS DONOTIMPORT4,
		ACLD.Approved_Contract_Changes AS DONOTIMPORT5,
		ACLD.Total_Billed AS DONOTIMPORT6,
		ACLD.Receivable_Adjustment AS DONOTIMPORT7,
		ACLD.Retainage_Held AS DONOTIMPORT8,
		ACLD.Retainage_Billed AS DONOTIMPORT9,
		ACL.[Format] AS DONOTIMPORT10,
		ACLD.Cash_Receipt AS DONOTIMPORT11,
		CAST(ACL.Date_Stamp AS DATE) AS DONOTIMPORT12,
		ACL.Row_ID AS DONOTIMPORT13,
		ACL.Contract AS LEGACY_CONTRACT
	FROM
		--[MAP].[T_TRANS_JOB] TJ
		--LEFT JOIN [s300].[CNC_ACTIVE__CONTRACT] AC ON TJ.DATA_FOLDER_ID = AC.Data_Folder_Id AND TJ.LEGACY_JOB_ID = AC.Contract
		--LEFT JOIN [s300].[CNC_ACTIVE__CONTRACT_ITEM] ACL ON AC.DATA_FOLDER_ID = ACL.Data_Folder_Id AND AC.Contract = ACL.Contract
		--LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_ITEM_DERIVED] ACLD ON ACL.Data_Folder_Id = ACLD.Data_Folder_Id AND ACL.Contract = ACLD.Contract AND ACL.Contract_Item = ACLD.Contract_Item
		--LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON TJ.DATA_FOLDER_ID = TE.DATA_FOLDER_ID
		--LEFT JOIN [MAP].[T_TRANS_CUSTOMER] TC ON ACL.Customer = TC.LEGACY_CUSTOMER_ID AND ACL.Data_Folder_Id = TC.DATA_FOLDER_ID
		[s300].[CNC_ACTIVE__CONTRACT_ITEM] ACL
		LEFT JOIN [s300].[ARM_MASTER__CUSTOMER] C ON ACL.Data_Folder_Id = C.Data_Folder_Id and ACL.Customer = C.Customer
		LEFT JOIN [s300].[CNC_ACTIVE__CONTRACT] AC ON ACL.Data_Folder_Id = AC.Data_Folder_Id AND ACL.Contract = AC.Contract
		LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_ITEM_DERIVED] ACLD ON ACL.Data_Folder_Id = ACLD.Data_Folder_ID AND ACL.Contract = ACLD.Contract AND ACL.Contract_Item = ACLD.Contract_Item
		LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_DERIVED] ACD ON AC.Data_Folder_Id = ACD.Data_Folder_Id AND AC.Contract = ACD.Contract
		LEFT JOIN [s300].[JCM_MASTER__JOB] J ON ACL.Data_Folder_Id = J.Data_Folder_Id AND ACL.Job = J.Job
		--LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON AC.Data_Folder_Id = TJ.DATA_FOLDER_ID AND AC.Contract = TJ.LEGACY_JOB_ID
		LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON ACL.Data_Folder_Id = TJ.DATA_FOLDER_ID AND ACL.JOB = TJ.LEGACY_JOB_ID
		LEFT JOIN [MAP].[T_TRANS_CUSTOMER] TC ON ACL.Data_Folder_Id = TC.DATA_FOLDER_ID AND ACL.Customer = TC.LEGACY_CUSTOMER_ID
		LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON TJ.DATA_FOLDER_ID = TE.DATA_FOLDER_ID
	WHERE
		TJ.INCLUDE_JOB = 1

	UNION ALL

	SELECT --REVISION
		ACL.Data_Folder_Id AS DONOTIMPORT1,
		--ACL.Contract AS PROJECTCONTRACTID,
		--TJ.NEW_JOB_ID AS PROJECTCONTRACTID,
		CASE WHEN CHARINDEX('-', AC.Contract) * CHARINDEX('-', TJ.NEW_JOB_ID) > 0
		  THEN LEFT(TJ.NEW_JOB_ID, CHARINDEX('-', TJ.NEW_JOB_ID) - 1) + SUBSTRING(AC.Contract, CHARINDEX('-', AC.Contract), LEN(AC.Contract))
		  ELSE AC.Contract END AS PROJECTCONTRACTID,
		ACL.Contract_Item AS PROJECTCONTRACTLINEID,
		ACL.Description AS NAME,
		TJ.NEW_JOB_ID AS PROJECTID,
		'' AS ITEMID,
		ACL.Description AS DESCRIPTION,
		COALESCE(CAST(ACL.Approval_Date AS DATE),CAST(ACL.Date_Stamp AS DATE)) AS CONTRACTLINEDATE,
		ACL.Default_Revenue_Account AS GLACCOUNTID,
		ACL.Retainage_Percent AS RETAINAGEPERCENTAGE,
		'true' AS BILLABLE,
		'active' AS STATUS,
		CASE WHEN ACL.Billing_Type IS NULL THEN ''
			 WHEN ACL.Billing_Type IN ('Progress Billing', 'Lump Sum') THEN 'Progress'
			 ELSE 'TM' END AS BILLINGTYPE,
		CASE WHEN ACL.Billing_Type = 'Cost Plus to Maximum' THEN 'Specified amount'
			 WHEN ACL.Billing_Type = 'Time & Materials' THEN 'No maximum'
			 ELSE '' END AS MAXIMUMBILLING,
		COALESCE(CASE WHEN ACL.Billing_Type = 'Cost Plus to Maximum'
				 THEN ACLD.Revised_Contract
				 WHEN ACL.Billing_Type = 'Time & Materials'
				 THEN 0 ELSE NULL END, 0) AS MAXIMUMBILLINGAMOUNT,
		ACL.Markup_Table AS DEFAULTRATETABLEID,
		ACL.Rate_Table_Labor AS TSRATETABLEID,
		ACL.Rate_Table_Subcontract AS PORATETABLEID,
		ACL.Rate_Table_Material AS APRATETABLEID,
		ACL.Rate_Table_Equipment AS GLRATETABLEID,
		ACL.Rate_Table_Other AS CCRATETABLEID,
		'' AS DEPARTMENTID,
		CASE WHEN ACLD.Approved_Contract_Changes <> 0 THEN 'revision'
			ELSE NULL END AS ENTRY_WFTYPE,
		TJ.NEW_JOB_ID AS ENTRY_PROJECTID,
		'' AS ENTRY_TASKID,
		'' AS ENTRY_COSTTYPEID,
		CASE WHEN ACLD.Approved_Contract_Changes <> 0 THEN 'Contract CO Item'
			ELSE NULL END AS ENTRY_ITEMID,
		ACLD.Approved_Contract_Changes AS ENTRY_PRICE,
		CAST(COALESCE(ACL.Approval_Date, ACL.Date_Stamp) AS DATE) AS ENTRY_PRICEEFFECTIVEDATE,
		'' AS ENTRY_MEMO,
		'' AS ENTRY_DEPARTMENTID,
		'' AS TASKID,
		'' AS COSTTYPEID,
		TC.NEW_CUSTOMER_ID AS ENTRY_CUSTOMERID,
		'LG_PROJECT|' + ACL.Job AS DONOTIMPORT2,
		'LG_CUST|' + ACL.Customer AS DONOTIMPORT3,
		ACLD.Revised_Contract AS DONOTIMPORT4,
		ACLD.Approved_Contract_Changes AS DONOTIMPORT5,
		ACLD.Total_Billed AS DONOTIMPORT6,
		ACLD.Receivable_Adjustment AS DONOTIMPORT7,
		ACLD.Retainage_Held AS DONOTIMPORT8,
		ACLD.Retainage_Billed AS DONOTIMPORT9,
		ACL.[Format] AS DONOTIMPORT10,
		ACLD.Cash_Receipt AS DONOTIMPORT11,
		CAST(ACL.Date_Stamp AS DATE) AS DONOTIMPORT12,
		ACL.Row_ID AS DONOTIMPORT13,
		ACL.Contract AS LEGACY_CONTRACT
	FROM
		--[MAP].[T_TRANS_JOB] TJ
		--LEFT JOIN [s300].[CNC_ACTIVE__CONTRACT] AC ON TJ.DATA_FOLDER_ID = AC.Data_Folder_Id AND TJ.LEGACY_JOB_ID = AC.Contract
		--LEFT JOIN [s300].[CNC_ACTIVE__CONTRACT_ITEM] ACL ON AC.DATA_FOLDER_ID = ACL.Data_Folder_Id AND AC.Contract = ACL.Contract
		--LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_ITEM_DERIVED] ACLD ON
		--	ACL.Data_Folder_Id = ACLD.Data_Folder_Id
		--	AND ACL.Contract = ACLD.Contract
		--	AND ACL.Contract_Item = ACLD.Contract_Item
		--LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON TJ.DATA_FOLDER_ID = TE.DATA_FOLDER_ID
		--LEFT JOIN [MAP].[T_TRANS_CUSTOMER] TC ON ACL.Customer = TC.LEGACY_CUSTOMER_ID AND ACL.Data_Folder_Id = TC.DATA_FOLDER_ID
		[s300].[CNC_ACTIVE__CONTRACT_ITEM] ACL
		LEFT JOIN [s300].[ARM_MASTER__CUSTOMER] C ON ACL.Data_Folder_Id = C.Data_Folder_Id and ACL.Customer = C.Customer
		LEFT JOIN [s300].[CNC_ACTIVE__CONTRACT] AC ON ACL.Data_Folder_Id = AC.Data_Folder_Id AND ACL.Contract = AC.Contract
		LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_ITEM_DERIVED] ACLD ON ACL.Data_Folder_Id = ACLD.Data_Folder_ID AND ACL.Contract = ACLD.Contract AND ACL.Contract_Item = ACLD.Contract_Item
		LEFT JOIN [s300].[CNA_ACTIVE__CONTRACT_DERIVED] ACD ON AC.Data_Folder_Id = ACD.Data_Folder_Id AND AC.Contract = ACD.Contract
		LEFT JOIN [s300].[JCM_MASTER__JOB] J ON ACL.Data_Folder_Id = J.Data_Folder_Id AND ACL.Job = J.Job
		--LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON AC.Data_Folder_Id = TJ.DATA_FOLDER_ID AND AC.Contract = TJ.LEGACY_JOB_ID
		LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON ACL.Data_Folder_Id = TJ.DATA_FOLDER_ID AND ACL.JOB = TJ.LEGACY_JOB_ID
		LEFT JOIN [MAP].[T_TRANS_CUSTOMER] TC ON ACL.Data_Folder_Id = TC.DATA_FOLDER_ID AND ACL.Customer = TC.LEGACY_CUSTOMER_ID
		LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON TJ.DATA_FOLDER_ID = TE.DATA_FOLDER_ID
	WHERE
		TJ.INCLUDE_JOB = 1
		) B
WHERE
	B.ENTRY_WFTYPE IS NOT NULL
	AND B.ENTRY_PRICE != 0;
	--AND B.PROJECTID LIKE('%1737%') AND B.DONOTIMPORT1 = 'prem'
	--AND B.PROJECTCONTRACTID LIKE('%-1735-MINIP%')
