--AS OF 05-11-2026
--PROJECT ESTIMATES
DECLARE @EffectiveDate DATE;
SET @EffectiveDate = (
    SELECT CONVERT(DATE, F.FIELD_VALUE, 23)  -- 23 = yyyy-mm-dd
    FROM [MAP].[E_USEFUL_FIELDS] F
    WHERE F.FIELD_NAME = 'GL03_DETAIL_STOP'
);


SELECT
	A.DONOTIMPORT1 AS DONOTIMPORT,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.PJESTIMATEID ELSE '' END AS PJESTIMATEID,
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.DESCRIPTION ELSE '' END AS 'DESCRIPTION',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.STATUS ELSE '' END AS 'STATUS',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.ISPRIMARY ELSE '' END AS 'ISPRIMARY',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.PJESTIMATETYPENAME ELSE '' END AS 'PJESTIMATETYPENAME',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.POSTED ELSE '' END AS 'POSTED',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.GLBUDGETID ELSE '' END AS 'GLBUDGETID',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.POSTTO ELSE '' END AS 'POSTTO',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN FORMAT(A.ESTIMATEDATE, 'yyyy-MM-dd') ELSE '' END AS 'ESTIMATEDATE',
	CASE WHEN (ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) = 1 THEN A.PROJECTID ELSE '' END AS 'PROJECTID',
	(ROW_NUMBER() OVER (PARTITION BY A.PROJECTID ORDER BY A.PROJECTID, A.PJESTIMATEENTRY_LINENO)) AS PJESTIMATEENTRY_LINENO,
	A.PJESTIMATEENTRY_WFTYPE,
	A.PJESTIMATEENTRY_TASKID,
	A.PJESTIMATEENTRY_COSTTYPEID,
	A.PJESTIMATEENTRY_ITEMID,
	A.PJESTIMATEENRY_UNITCOST,
	A.PJESTIMATEENTRY_QTY,
	A.PJESTIMATEENTRY_AMOUNT,
	A.PJESTIMATEENTRY_EUOM,
	A.PJESTIMATEENTRY_PRODUCTIONUNITS,
	A.PJESTIMATEENTRY_ACCOUNTNO,
	A.PJESTIMATEENTRY_EFFECTIVEDATE,
	A.PJESTIMATEENTRY_LOCATIONID,
	A.PJESTIMATEENTRY_PROJECTID,
	A.PJESTIMATEENTRY_DEPARTMENTID,
	A.PJESTIMATEENTRY_CLASSID,
	A.DONOTIMPORT2,
	A.DONOTIMPORT3,
	A.DONOTIMPORT4,
	A.DONOTIMPORT5,
	A.DONOTIMPORT6,
	--A.DONOTIMPORT7,
	--A.DONOTIMPORT8,
	A.DONOTIMPORT9
FROM
	(
	SELECT
		JCMC.Data_Folder_Id AS DONOTIMPORT1,
		TJ.NEW_JOB_ID AS PJESTIMATEID,
		TJ.NEW_JOB_ID + ' Estimate' AS DESCRIPTION,
		'active' AS STATUS,
		'true' AS ISPRIMARY,
		'Current Estimate' AS PJESTIMATETYPENAME,
		'TRUE' AS POSTED,
		'Project Estimate' AS GLBUDGETID,
		'Estimate date' AS POSTTO,
		@EffectiveDate AS ESTIMATEDATE,
		TJ.NEW_JOB_ID AS PROJECTID,
		'A' AS PJESTIMATEENTRY_LINENO,
		'original' AS PJESTIMATEENTRY_WFTYPE,
		TCC.NEW_COST_CODE_ID AS PJESTIMATEENTRY_TASKID,
		TCT.NEW_COST_TYPE_ID AS PJESTIMATEENTRY_COSTTYPEID,
		'Beginning Balance' AS PJESTIMATEENTRY_ITEMID,
		'' AS PJESTIMATEENRY_UNITCOST,
		JCMC.Original_Estimate_Units AS PJESTIMATEENTRY_QTY,
		JCMC.Original_Estimate AS PJESTIMATEENTRY_AMOUNT,
		JCMC.Cost_Unit_Description AS PJESTIMATEENTRY_EUOM,
		JCMCC.Orig_Production_Units_Est AS PJESTIMATEENTRY_PRODUCTIONUNITS,
		CASE WHEN JCMC.Category = 'L' THEN '5100' --THIS FIELD WAS ALL CUSTOM FOR SILVERLINING
			WHEN JCMC.Category = 'S' THEN '5120'
			WHEN JCMC.Category = 'M' THEN '5110' ELSE '5130' END AS PJESTIMATEENTRY_ACCOUNTNO,
		@EffectiveDate AS PJESTIMATEENTRY_EFFECTIVEDATE,
		TE.NEW_ENTITY_ID AS PJESTIMATEENTRY_LOCATIONID,
		TJ.NEW_JOB_ID AS PJESTIMATEENTRY_PROJECTID,
		TD.NEW_DEPARTMENT_ID AS PJESTIMATEENTRY_DEPARTMENTID,
		'' AS PJESTIMATEENTRY_CLASSID,
		JCMC.Job AS DONOTIMPORT2,
		JCMC.Extra AS DONOTIMPORT3,
		JCMC.Cost_Code AS DONOTIMPORT4,
		JCMC.Category AS DONOTIMPORT5,
		JCMC.Cost_Account AS DONOTIMPORT6,
		--JCMC.Misc_Title_1 AS DONOTIMPORT7,
		--JCMC.Misc_Title_2 AS DONOTIMPORT8,
		JCM.Last_Cost_Update AS DONOTIMPORT9
	FROM
		[s300].[JCM_MASTER__CATEGORY] JCMC
		LEFT JOIN [s300].[JCM_MASTER__JOB] JCM ON JCMC.Job = JCM.Job AND JCMC.Data_Folder_Id = JCM.Data_Folder_Id
		LEFT JOIN [s300].[JCM_MASTER__COST_CODE] JCMCC ON
			JCMC.Job = JCMCC.Job AND
			JCMC.Extra = JCMCC.Extra AND
			JCMC.Cost_Code = JCMCC.Cost_Code AND
			JCMC.Data_Folder_Id = JCMCC.Data_Folder_Id
		LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON JCMC.Job = TJ.LEGACY_JOB_ID AND JCMC.Data_Folder_Id = TJ.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON JCMC.Cost_Code = TCC.LEGACY_COST_CODE_ID AND JCMC.Data_Folder_Id = TCC.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_COST_TYPE] TCT ON JCMC.Category = TCT.LEGACY_COST_TYPE_ID AND JCMC.Data_Folder_Id = TCT.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_DEPARTMENT] TD ON JCM.Cost_Account_Prefix = TD.LEGACY_DEPARTMENT_ID AND JCM.Data_Folder_Id = TD.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON JCMC.Data_Folder_Id = TE.DATA_FOLDER_ID
	WHERE
		TJ.INCLUDE_JOB = '1'
		AND CAST(JCMC.Original_Estimate AS DECIMAL(18,6)) != 0
		
	UNION ALL
	
	SELECT
		JCMC.Data_Folder_Id AS DONOTIMPORT1,
		TJ.NEW_JOB_ID AS PJESTIMATEID,
		TJ.NEW_JOB_ID + ' Estimate' AS DESCRIPTION,
		'active' AS STATUS,
		'true' AS ISPRIMARY,
		'Current Estimate' AS PJESTIMATETYPENAME,
		'TRUE' AS POSTED,
		'Project Estimate' AS GLBUDGETID,
		'Estimate date' AS POSTTO,
		@EffectiveDate AS ESTIMATEDATE,
		TJ.NEW_JOB_ID AS PROJECTID,
		'B' AS PJESTIMATEENTRY_LINENO,
		'approved change' AS PJESTIMATEENTRY_WFTYPE,
		TCC.NEW_COST_CODE_ID AS PJESTIMATEENTRY_TASKID,
		TCT.NEW_COST_TYPE_ID AS PJESTIMATEENTRY_COSTTYPEID,
		'Beginning Balance' AS PJESTIMATEENTRY_ITEMID,
		'' AS PJESTIMATEENRY_UNITCOST,
		JCMC.Approved_Est_Unit_Changes AS PJESTIMATEENTRY_QTY,
		JCMC.Approved_Estimate_Changes AS PJESTIMATEENTRY_AMOUNT,
		JCMC.Cost_Unit_Description AS PJESTIMATEENTRY_EUOM,
		JCMCC.Apprvd_Prodctn_Unit_Chgs AS PJESTIMATEENTRY_PRODUCTIONUNITS,
		CASE WHEN JCMC.Category = 'L' THEN '5100' --THIS FIELD WAS ALL CUSTOM FOR SILVERLINING
			WHEN JCMC.Category = 'S' THEN '5120'
			WHEN JCMC.Category = 'M' THEN '5110' ELSE '5130' END AS PJESTIMATEENTRY_ACCOUNTNO,
		@EffectiveDate AS PJESTIMATEENTRY_EFFECTIVEDATE,
		TE.NEW_ENTITY_ID AS PJESTIMATEENTRY_LOCATIONID,
		TJ.NEW_JOB_ID AS PJESTIMATEENTRY_PROJECTID,
		TD.NEW_DEPARTMENT_ID AS PJESTIMATEENTRY_DEPARTMENTID,
		'' AS PJESTIMATEENTRY_CLASSID,
		JCMC.Job AS DONOTIMPORT2,
		JCMC.Extra AS DONOTIMPORT3,
		JCMC.Cost_Code AS DONOTIMPORT4,
		JCMC.Category AS DONOTIMPORT5,
		JCMC.Cost_Account AS DONOTIMPORT6,
		--JCMC.Misc_Title_1 AS DONOTIMPORT7,
		--JCMC.Misc_Title_2 AS DONOTIMPORT8,
		JCM.Last_Cost_Update AS DONOTIMPORT9
	FROM
		[s300].[JCM_MASTER__CATEGORY] JCMC
		LEFT JOIN [s300].[JCM_MASTER__JOB] JCM ON JCMC.Job = JCM.Job AND JCMC.Data_Folder_Id = JCM.Data_Folder_Id
		LEFT JOIN [s300].[JCM_MASTER__COST_CODE] JCMCC ON
			JCMC.Job = JCMCC.Job AND
			JCMC.Extra = JCMCC.Extra AND
			JCMC.Cost_Code = JCMCC.Cost_Code AND
			JCMC.Data_Folder_Id = JCMCC.Data_Folder_Id
		LEFT JOIN [MAP].[T_TRANS_JOB] TJ ON JCMC.Job = TJ.LEGACY_JOB_ID AND JCMC.Data_Folder_Id = TJ.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_COST_CODE] TCC ON JCMC.Cost_Code = TCC.LEGACY_COST_CODE_ID AND JCMC.Data_Folder_Id = TCC.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_COST_TYPE] TCT ON JCMC.Category = TCT.LEGACY_COST_TYPE_ID AND JCMC.Data_Folder_Id = TCT.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_DEPARTMENT] TD ON JCM.Cost_Account_Prefix = TD.LEGACY_DEPARTMENT_ID AND JCM.Data_Folder_Id = TD.DATA_FOLDER_ID
		LEFT JOIN [MAP].[T_TRANS_ENTITY] TE ON JCMC.Data_Folder_Id = TE.DATA_FOLDER_ID
	WHERE
		TJ.INCLUDE_JOB = '1'
		AND CAST(JCMC.Approved_Estimate_Changes AS DECIMAL(18,6)) != 0		
		) A
--WHERE
--	A.PROJECTID = 'C-1524-ROTH2'
ORDER BY
	A.PROJECTID,
	A.PJESTIMATEENTRY_LINENO;