--THIS NEEDS UPDATED FOR CORRECTED ENTITY TRANSLATION JOIN, SEE THE GL3
--As of 03/06/2026
--PRIOR YEAR/S MONTHLY

DECLARE @StartDate DATE;
SET @StartDate = (
    SELECT CONVERT(DATE, F.FIELD_VALUE, 23)  -- 23 = yyyy-mm-dd
    FROM [MAP].[E_USEFUL_FIELDS] F
    WHERE F.FIELD_NAME = 'GL02_MONTHLY_START'
);

DECLARE @EndDate DATE;
SET @EndDate = (
    SELECT CONVERT(DATE, F.FIELD_VALUE, 23)  -- 23 = yyyy-mm-dd
    FROM [MAP].[E_USEFUL_FIELDS] F
    WHERE F.FIELD_NAME = 'GL02_MONTHLY_STOP'
);

SELECT
	'Entity: ' + AL.NEW_ENTITY_ID AS DONOTIMPORT,
	CASE WHEN AL.LINE_NO = 1 THEN AL.JOURNAL ELSE '' END AS JOURNAL,
	CASE WHEN AL.LINE_NO = 1 THEN FORMAT(AL.[DATE], 'yyyy-MM-dd') ELSE '' END AS [DATE],
	CASE WHEN AL.LINE_NO = 1 THEN AL.DESCRIPTION ELSE '' END AS DESCRIPTION,
	AL.REFERENCE_NO AS REFERENCE,
	AL.LINE_NO,
	AL.ACCT_NO,
	AL.LOCATION_ID,
	AL.DEPT_ID,
	AL.CLASS_ID,
	AL.DOCUMENT AS DOCUMENT,
	AL.MEMO AS MEMO,
	--AL.NET,
	CASE WHEN AL.DEBIT = 0 THEN '' ELSE FORMAT(AL.DEBIT, '0.00') END AS DEBIT,
	CASE WHEN AL.CREDIT = 0 THEN '' ELSE FORMAT(AL.CREDIT, '0.00') END AS CREDIT,
	AL.[STATUS],
	'S300_ACCT|' + AL.ORIG_ACCOUNT AS DONOTIMPORT,
	'S300_ACCT_DATE|' + FORMAT(AL.OG_DATE, 'yyyy-MM-dd') AS DONOTIMPORT,
	'S300_REF1|' + AL.REFERENCE_NO AS DONOTIMPORT,
	'S300_REF2|' + AL.Reference_2 AS DONOTIMPORT,
	'SI_ENT|' + AL.NEW_ENTITY_ID AS DONOTIMPORT,
	AL.DESCRIPTION AS DONOTIMPORT,
	ROUND(AL.DEBIT - AL.CREDIT,2) AS DONOTIMPORT
FROM
	(SELECT
		T.JOURNAL,
		T.[DATE],
		T.OG_DATE,
		T.DESCRIPTION,
		T.REFERENCE_NO,
		ROW_NUMBER() OVER (PARTITION BY T.NEW_ENTITY_ID, T.[DATE], T.DESCRIPTION ORDER BY T.NEW_ENTITY_ID, T.[DATE], T.DESCRIPTION, T.LOCATION_ID, T.REFERENCE_NO, T.MEMO_ORDER, T.ACCT_NO, T.LOCATION_ID) AS LINE_NO,
		ROW_NUMBER() OVER (PARTITION BY T.NEW_ENTITY_ID ORDER BY T.NEW_ENTITY_ID) AS ENTITY_ROW,
		T.ACCT_NO,
		T.LOCATION_ID,
		T.DEPT_ID,
		T.CLASS_ID,
		T.DOCUMENT,
		T.MEMO,
		T.MEMO_ORDER,
		SUM(T.DEBIT) + SUM(T.CREDIT) AS NET,
		CASE WHEN (SUM(T.DEBIT) + SUM(T.CREDIT)) >= 0 THEN (SUM(T.DEBIT) + SUM(T.CREDIT)) ELSE 0 END AS DEBIT,
		CASE WHEN (SUM(T.DEBIT) + SUM(T.CREDIT)) < 0 THEN (SUM(T.DEBIT) + SUM(T.CREDIT))*-1 ELSE 0 END AS CREDIT,
		T.[STATUS],
		T.Account AS ORIG_ACCOUNT,
		T.NEW_ENTITY_ID,
		T.Reference_2
	FROM
		(SELECT
			'OBJ' AS JOURNAL,
			EOMONTH(CT."Accounting_Date") AS [DATE],
			EOMONTH(CT."Accounting_Date") AS OG_DATE,
			--'Entity: ' + TA.NEW_ENTITY_ID + ' | Origin: ' + CT.Application_of_Origin + ' | Batch: ' + CT.Batch + ' | Batch Date: ' +  FORMAT(CT."Accounting_Date", 'yyyy-MM') + ' | Acct Date: ' + FORMAT(CT."Accounting_Date", 'yyyy-MM') AS DESCRIPTION,
			--'Entity: ' + TA.NEW_ENTITY_ID + ' | Origin: ' + COALESCE(CX.APPLICATION_OF_ORIGIN, CT.Application_of_Origin) + ' | Batch: ' + COALESCE(TBC.TO_BATCH_ALIAS, CT.Batch) + ' | Batch Date: ' +  FORMAT(COALESCE(CX.AD, CT."Accounting_Date"), 'yyyy-MM') + ' | Acct Date: ' + FORMAT(COALESCE(CX.AD, CT."Accounting_Date"), 'yyyy-MM') AS DESCRIPTION,
			--'Entity: ' + TA.NEW_ENTITY_ID + ' | Origin: ' + COALESCE(CT.Application_of_Origin,'') + ' | Batch: ' + COALESCE(TBC.TO_BATCH_ALIAS, CT.Batch) + ' | Batch Date: ' +  COALESCE((FORMAT(CT."Accounting_Date", 'yyyy-MM')),'') + ' | Acct Date: ' + COALESCE(FORMAT(CT."Accounting_Date", 'yyyy-MM'),'') AS DESCRIPTION,
			'Entity: ' + TA.NEW_ENTITY_ID + ' | Month_End: ' + FORMAT(EOMONTH(CT."Accounting_Date"), 'yyyy-MM') AS DESCRIPTION,
			'' AS REFERENCE_NO, 
			COALESCE(COALESCE(FFULL.NEW_BASE_ACCOUNT, FNF.NEW_BASE_ACCOUNT),'(MISSING)') AS ACCT_NO,
			COALESCE(LOC.NEW_LOCATION_ID, '') AS LOCATION_ID,
			COALESCE(DEPT.NEW_DEPARTMENT_ID, '') AS DEPT_ID,
			'' AS CLASS_ID,
			'' AS DOCUMENT,  --MAY NEED THIS ADDED BACK?
			'Entity: ' + TA.NEW_ENTITY_ID + ' | Month_End: ' + FORMAT(EOMONTH(CT."Accounting_Date"), 'yyyy-MM') AS MEMO,
			'Entity: ' + TA.NEW_ENTITY_ID + ' | Month_End: ' + FORMAT(EOMONTH(CT."Accounting_Date"), 'yyyy-MM') AS MEMO_ORDER,
			CT."Debit", 
			CT."Credit",
			'POSTED' AS [STATUS],
			CT."Account", 
			--CT."Application_of_Origin", 
			'' AS Application_of_Origin,
			--CT."Transaction_Desc", 
			'' AS Transaction_Desc,
			CT."Vendor", 
			--CT."AP_Invoice", 
			'' AS 'AP_INVOICE',
			--CT."Job",
			'' AS Job,
			CT."Customer", 
			--CT."AR_Invoice", 
			'' AS AR_INVOICE,
			CT."Accrual_or_Cash", 
			--CT."Reference_2",
			'' AS Reference_2,
			TA.NEW_ENTITY_ID
		FROM   
			[s300].[GLT_CURRENT__TRANSACTION] CT
			LEFT JOIN [MAP].[T_MASTER_ACCOUNT] MA ON CT.Account = MA.ACCOUNT AND CT.Data_Folder_Id = MA.Data_Folder_Id
			LEFT JOIN [MAP].[T_TRANS_ENTITY] TA ON CT.Data_Folder_Id = TA.DATA_FOLDER_ID --MAY HAVE TO CHANGE THIS
			LEFT JOIN MAP.T_TRANS_BASEACCT AS FFULL --THIS TRIES A FULL ACCOUNT MATCH IF TRANSLATION IS SET TO FULL
				ON FFULL.ACCT_MATCH_TYPE = 'FULL'
			   AND FFULL.LEGACY_BASE_ACCOUNT = MA.ACCOUNT
			   AND FFULL.Data_Folder_Id = MA.Data_Folder_Id
			LEFT JOIN MAP.T_TRANS_BASEACCT AS FNF --THIS TRIES A PARTIAL ACCOUNT MATCH IF TRANSLATION IS SET TO PARTIAL
				ON FNF.ACCT_MATCH_TYPE = 'BASE'
			   --AND FNF.LEGACY_BASE_ACCOUNT = CONCAT(MA.BASEACCOUNT, '.', MA.SUFFIX)
			   AND FNF.LEGACY_BASE_ACCOUNT = MA.BASEACCOUNT
			   AND FNF.Data_Folder_Id = MA.Data_Folder_Id
			   AND FFULL.LEGACY_BASE_ACCOUNT IS NULL
			LEFT JOIN (
				SELECT DISTINCT
					LEGACY_DEPARTMENT_ID,
					NEW_DEPARTMENT_ID,
					Data_Folder_Id
				FROM
					[MAP].[T_TRANS_DEPARTMENT]
				WHERE
					LEGACY_DEPARTMENT_ID != ''
					AND NEW_DEPARTMENT_ID != '') DEPT ON MA.PREFIXABC = DEPT.LEGACY_DEPARTMENT_ID AND MA.Data_Folder_Id = dept.Data_Folder_ID
			LEFT JOIN (
				SELECT DISTINCT
					LEGACY_LOCATION_ID,
					NEW_LOCATION_ID,
					Data_Folder_Id
				FROM
					[MAP].[T_TRANS_LOCATION]
				WHERE
					LEGACY_LOCATION_ID != ''
					AND NEW_LOCATION_ID != '') LOC ON MA.PREFIXABC = LOC.LEGACY_LOCATION_ID AND MA.Data_Folder_Id = LOC.Data_Folder_Id
			LEFT JOIN [MAP].[T_TRANS_BATCH_COMBINE] TBC ON CT.Batch = TBC.SOURCE_BATCH --AND CT.Data_Folder_Id = TBC.Data_Folder_Id --Add Data Folder Id to TBC
			--LEFT JOIN (
			--	SELECT DISTINCT
			--		CT2.Batch,
			--		CT2.Application_of_Origin,
			--		CT2."Accounting_Date" AS AD
			--	FROM 
			--		s300.GLT_CURRENT__TRANSACTION CT2) CX ON TBC.TO_BATCH_ID = CX.BATCH
			LEFT JOIN (
				SELECT
					d.Data_Folder_Id,
					d.Batch,
					d.Application_of_Origin,
					d.AD
				FROM (
					SELECT
						CT2.Data_Folder_Id,
						CT2.Batch,
						CT2.Application_of_Origin,
						CT2."Accounting_Date" AS AD,
						ROW_NUMBER() OVER (
							PARTITION BY Ct2.Data_Folder_ID, CT2.Batch
							ORDER BY CT2."Accounting_Date" DESC
						) AS rn
					FROM s300.GLT_CURRENT__TRANSACTION CT2
				) d
				WHERE d.rn = 1
			) CX ON TBC.TO_BATCH_ID = CX.Batch
		WHERE  
			(CT."Accounting_Date">=@StartDate AND CT."Accounting_Date"<=@EndDate) 
			AND CT."Accrual_or_Cash"='Accrual'
			--AND LEFT(CT."Account",2) IN('01','02')
			--THE BELOW ACCOUNTS NET TO ZERO IN THE SAME MONTH. NEED BETTER WAY TO EXCLUDE
			--AND CT."Account" NOT IN('01-01-00-10100.000','01-01-00-66100.020','01-02-00-66100.020','01-95-00-66100.020','01-95-00-23136.024','01-94-85-78250.000')
			) T
	GROUP BY
		T.JOURNAL,
		T.[DATE],
		T.OG_DATE,
		T.DESCRIPTION,
		T.REFERENCE_NO,
		T.ACCT_NO,
		T.LOCATION_ID,
		T.DEPT_ID,
		T.CLASS_ID,
		T.DOCUMENT,
		T.MEMO,
		T.MEMO_ORDER,
		T.[STATUS],
		T.Account,
		T.NEW_ENTITY_ID,
		T.Reference_2
	HAVING
		ROUND(SUM(T.DEBIT) + SUM(T.CREDIT),2) != 0) AL
ORDER BY 
	AL.NEW_ENTITY_ID,
	AL.[DATE], 
	AL.DESCRIPTION,
	AL.LOCATION_ID,
	AL.REFERENCE_NO,
	AL.MEMO_ORDER,
	AL.ACCT_NO, 
	AL.DOCUMENT;