--DATA FOLDER TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_DATA_FOLDER') BEGIN
CREATE TABLE MAP.T_TRANS_DATA_FOLDER (LEGACY_DATA_FOLDER_ID VARCHAR(50), LEGACY_DATA_FOLDER_NAME VARCHAR(200), NEW_ID VARCHAR(50), NEW_NAME VARCHAR(100), DESTINATION VARCHAR(50), INCLUDE_DATA_FOLDER BIT NOT NULL DEFAULT 1);
INSERT INTO MAP.T_TRANS_DATA_FOLDER (LEGACY_DATA_FOLDER_ID, LEGACY_DATA_FOLDER_NAME, NEW_ID, NEW_NAME, DESTINATION, INCLUDE_DATA_FOLDER)
SELECT DISTINCT
	SI.Data_Folder_Id,
	SI.Section_Id,
	SI.Data_Folder_Id,
	SI.Section_Id,
	'ENTITY', --PUT 'ENTITY' OR 'LOCATION'
	'1' --TO INCLUDE
FROM
	[s300Log].[Sage300Import] SI;
END
GO
