--JOB TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_JOB') BEGIN
CREATE TABLE MAP.T_TRANS_JOB (LEGACY_JOB_ID VARCHAR(50), LEGACY_JOB_NAME VARCHAR(200), LEGACY_JOB_STATUS VARCHAR(20), NEW_JOB_ID VARCHAR(50), NEW_JOB_NAME VARCHAR(200), LEGACY_DATA_FOLDER_ID VARCHAR(100), INCLUDE_JOB BIT NOT NULL DEFAULT 0, DATA_FOLDER_ID VARCHAR(50), LEGACY_EXTRA_ID VARCHAR(50), NEW_ENTITY_ID VARCHAR(50), NEW_DEPARTMENT_ID VARCHAR(50), NEW_CLASS_ID VARCHAR(50), NEW_CUSTOMER_ID VARCHAR(50), NEW_PM_ID VARCHAR(50));
INSERT INTO MAP.T_TRANS_JOB (LEGACY_JOB_ID, LEGACY_JOB_NAME, LEGACY_JOB_STATUS, NEW_JOB_ID, NEW_JOB_NAME, LEGACY_DATA_FOLDER_ID, INCLUDE_JOB, DATA_FOLDER_ID, LEGACY_EXTRA_ID, NEW_ENTITY_ID, NEW_DEPARTMENT_ID, NEW_CLASS_ID, NEW_CUSTOMER_ID, NEW_PM_ID)
SELECT J.JOB, J.DESCRIPTION, J.STATUS, J.JOB, J.DESCRIPTION, J.Data_Folder_Id, CASE WHEN J.Status NOT IN ('Closed') THEN 1 ELSE 0 END, DATA_FOLDER_ID, '', '', '', '', '', ''
FROM
	[s300].[JCM_MASTER__JOB] J;
--ADD EXTRA INTO JOB Translation
INSERT INTO [MAP].[T_TRANS_JOB](LEGACY_DATA_FOLDER_ID, DATA_FOLDER_ID, LEGACY_JOB_ID, LEGACY_EXTRA_ID, LEGACY_JOB_NAME, NEW_JOB_NAME, INCLUDE_JOB)
SELECT Data_Folder_Id, Data_Folder_Id, Job, Extra, Description, Description, 0 FROM [s300].[JCM_MASTER__EXTRA]
END
GO
