--CUSTOMER TRANSLATION - DEFAULTS TO INACTIVE CUSTOMERS BEING EXCLUDED
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_CUSTOMER') BEGIN
CREATE TABLE MAP.T_TRANS_CUSTOMER (DATA_FOLDER_ID VARCHAR(50), LEGACY_CUSTOMER_ID VARCHAR(50), LEGACY_CUSTOMER_NAME VARCHAR(200), LEGACY_CUSTOMER_STATUS VARCHAR(50), LEGACY_CUSTOMER_TYPE VARCHAR(50), NEW_CUSTOMER_ID VARCHAR(50), NEW_CUSTOMER_TYPE VARCHAR(50), INCLUDE_CUSTOMER BIT NOT NULL DEFAULT 0, ON_OPEN_AR VARCHAR(3), ON_OPEN_OE VARCHAR(3), ON_OPEN_OTHER VARCHAR(3));
INSERT INTO MAP.T_TRANS_CUSTOMER (DATA_FOLDER_ID, LEGACY_CUSTOMER_ID, LEGACY_CUSTOMER_NAME, LEGACY_CUSTOMER_STATUS, LEGACY_CUSTOMER_TYPE, NEW_CUSTOMER_ID, NEW_CUSTOMER_TYPE, INCLUDE_CUSTOMER, ON_OPEN_AR, ON_OPEN_OE, ON_OPEN_OTHER)
SELECT
	C.DATA_FOLDER_ID,
	C.CUSTOMER,
	C.[NAME],
	C.[STATUS],
	C.CUSTOMER_TYPE,
	C.CUSTOMER,
	C.CUSTOMER_TYPE,
	CASE WHEN C.STATUS IN('Active') THEN 1 ELSE 0 END,
	'-',
	'-',
	'-'
FROM
	[s300].[ARM_MASTER__CUSTOMER] C;
END
GO
