--VENDOR TRANSLATION - THIS WILL BY DEFAULT SET TO ACTIVE ANY VENDORS THAT ARE ACTIVE
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_VENDOR') BEGIN
CREATE TABLE MAP.T_TRANS_VENDOR (DATA_FOLDER_ID VARCHAR(50), LEGACY_VENDOR_ID VARCHAR(50), LEGACY_VENDOR_NAME VARCHAR(200), LEGACY_VENDOR_STATUS VARCHAR(50), LEGACY_VENDOR_TYPE VARCHAR(50), NEW_VENDOR_ID VARCHAR(50), NEW_VENDOR_TYPE VARCHAR(50), INCLUDE_VENDOR BIT NOT NULL DEFAULT 0, ON_OPEN_AP BIT NOT NULL DEFAULT 0, ON_OPEN_COMMITMENT BIT NOT NULL DEFAULT 0, ON_OPEN_OTHER BIT NOT NULL DEFAULT 0);
INSERT INTO MAP.T_TRANS_VENDOR (DATA_FOLDER_ID, LEGACY_VENDOR_ID, LEGACY_VENDOR_NAME, LEGACY_VENDOR_STATUS, LEGACY_VENDOR_TYPE, NEW_VENDOR_ID, NEW_VENDOR_TYPE, INCLUDE_VENDOR, ON_OPEN_AP, ON_OPEN_COMMITMENT, ON_OPEN_OTHER)
SELECT
	V.DATA_FOLDER_ID,
	V.VENDOR,
	V.[NAME],
	CASE WHEN V.INACTIVE = '1' THEN 'INACTIVE' ELSE 'ACTIVE' END,
	V.[TYPE],
	V.VENDOR,
	V.[TYPE],
	CASE WHEN V.INACTIVE = 1 THEN 0 ELSE 1 END,
	0, 0, 0
FROM
	[s300].[APM_MASTER__VENDOR] V;
END
GO
