--COST CODE TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_COST_CODE') BEGIN
CREATE TABLE MAP.T_TRANS_COST_CODE (LEGACY_COST_CODE_ID VARCHAR(50), LEGACY_COST_CODE_NAME VARCHAR(100), NEW_COST_CODE_ID VARCHAR(50), NEW_COST_CODE_NAME VARCHAR(100), NEW_ITEM_ID VARCHAR(50), DATA_FOLDER_ID VARCHAR(50));
INSERT INTO MAP.T_TRANS_COST_CODE (LEGACY_COST_CODE_ID, LEGACY_COST_CODE_NAME, NEW_COST_CODE_ID, NEW_COST_CODE_NAME, NEW_ITEM_ID, DATA_FOLDER_ID)
SELECT COST_CODE, [DESCRIPTION], COST_CODE, [DESCRIPTION], COST_CODE, DATA_FOLDER_ID FROM [s300].[JCM_MASTER__STANDARD_COST_CODE];
END
GO
