--COST TYPE TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_COST_TYPE') BEGIN
CREATE TABLE MAP.T_TRANS_COST_TYPE (LEGACY_COST_TYPE_ID VARCHAR(50), LEGACY_COST_TYPE_NAME VARCHAR(100), NEW_COST_TYPE_ID VARCHAR(50),NEW_ITEM_ID VARCHAR(50), NEW_INTACCT_GL_ACCOUNT VARCHAR(50),DATA_FOLDER_ID VARCHAR(50));
INSERT INTO MAP.T_TRANS_COST_TYPE (LEGACY_COST_TYPE_ID, LEGACY_COST_TYPE_NAME, NEW_COST_TYPE_ID, NEW_ITEM_ID,NEW_INTACCT_GL_ACCOUNT, DATA_FOLDER_ID)
SELECT Category, [DESCRIPTION], Category, Accumulate_As, Cost_Account_A, DATA_FOLDER_ID FROM [s300].[JCM_MASTER__STANDARD_CATEGORY];
END
GO
