--BATCH COMBINE
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_BATCH_COMBINE') BEGIN
CREATE TABLE MAP.T_TRANS_BATCH_COMBINE (SOURCE_BATCH VARCHAR(50), PERIOD DATE, BATCH_PER VARCHAR(50), DEBIT DECIMAL(18,2), CREDIT DECIMAL(18,2), NET DECIMAL(18,2), NET_ABS DECIMAL(18,2), TO_BATCH_ALIAS VARCHAR(50), TO_BATCH_ID VARCHAR(50))
INSERT INTO MAP.T_TRANS_BATCH_COMBINE (SOURCE_BATCH, PERIOD, BATCH_PER, DEBIT, CREDIT, NET, NET_ABS, TO_BATCH_ALIAS, TO_BATCH_ID)
	SELECT
		CT.BATCH,
		EOMONTH(CT.Accounting_Date) AS PERIOD,
		CT.BATCH +' | ' + FORMAT(EOMONTH(CT.Accounting_Date), 'yyyy-MM') AS BATCH_PER,
		SUM(CT.Debit) AS DEBIT,
		SUM(CT.Credit *-1) AS CREDIT,
		SUM(ROUND(CT.Debit + CT.Credit,2)) AS NET,
		ABS(SUM(ROUND(CT.Debit + CT.Credit,2))) AS NET_ABS,
		CT.BATCH,
		CT.BATCH
	FROM
		s300.GLT_CURRENT__TRANSACTION CT
	WHERE
		(CT."Accounting_Date" >= {d '2025-01-01'} AND CT."Accounting_Date"<={d '2025-11-30'})
		AND CT."Accrual_or_Cash"='Accrual'
		AND LEFT(CT."Account",2) IN ('01','02')
	GROUP BY
		CT.BATCH,
		EOMONTH(CT.Accounting_Date),
		CT.BATCH +' | ' + FORMAT(EOMONTH(CT.Accounting_Date), 'yyyy-MM')
	HAVING
		SUM(ROUND(CT.Debit + CT.Credit,2)) != 0
	ORDER BY
		ABS(SUM(ROUND(CT.Debit + CT.Credit,2)))
END
GO
