--EMPLOYEE TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_EMPLOYEE') BEGIN
CREATE TABLE MAP.T_TRANS_EMPLOYEE (LEGACY_EMPLOYEE_ID VARCHAR(50), LEGACY_EMPLOYEE_NAME VARCHAR(100), LEGACY_EMPLOYEE_STATUS VARCHAR(50), NEW_EMPLOYEE_ID VARCHAR(50), INCLUDE_EMPLOYEE BIT NOT NULL DEFAULT 0, DATA_FOLDER_ID VARCHAR(50));
INSERT INTO MAP.T_TRANS_EMPLOYEE (LEGACY_EMPLOYEE_ID, LEGACY_EMPLOYEE_NAME, LEGACY_EMPLOYEE_STATUS, NEW_EMPLOYEE_ID, INCLUDE_EMPLOYEE, DATA_FOLDER_ID)
SELECT EMP.EMPLOYEE, EMP.EMPLOYEE_NAME, CASE WHEN EMP.Termination_Date IS NULL THEN 'Active' ELSE 'Inactive' END, EMP.EMPLOYEE, CASE WHEN EMP.Termination_Date IS NULL THEN 1 ELSE 0 END, DATA_FOLDER_ID FROM [s300].[PRM_MASTER__EMPLOYEE] EMP;
END
GO
