--DEPARTMENT TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_DEPARTMENT') BEGIN
CREATE TABLE MAP.T_TRANS_DEPARTMENT (DATA_FOLDER_ID VARCHAR(50), LEGACY_DEPARTMENT_ID VARCHAR(50), NEW_DEPARTMENT_ID VARCHAR(50));
INSERT INTO MAP.T_TRANS_DEPARTMENT (DATA_FOLDER_ID, LEGACY_DEPARTMENT_ID, NEW_DEPARTMENT_ID)
SELECT DISTINCT
	MA.DATA_FOLDER_ID,
	MA.PrefixABC,
	MA.PrefixABC
FROM
	[MAP].[T_MASTER_ACCOUNT] MA
END
GO
