--COMMON FIELDS
--THIS CREATES SOME COMMONLY USED FIELDS THAT ARE USED LATER
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'E_USEFUL_FIELDS')
BEGIN
    CREATE TABLE MAP.E_USEFUL_FIELDS (FIELD_NAME VARCHAR(50), FIELD_VALUE VARCHAR(100));
    INSERT INTO MAP.E_USEFUL_FIELDS (FIELD_NAME, FIELD_VALUE)
    VALUES
    ('COMPANY_ID', 'XXX'),
    ('GL01_BALANCE_END', '2024-12-31'),
    ('GL02_MONTHLY_START', '2025-01-01'),
    ('GL02_MONTHLY_STOP', '2025-12-31'),
    ('GL03_DETAIL_START', '2026-01-01'),
    ('GL03_DETAIL_STOP', '2026-02-28');
END
GO
