--COMMON FIELDS
--THIS CREATES SOME COMMONLY USED FIELDS THAT ARE USED LATER
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'E_USEFUL_FIELDS')
BEGIN
    CREATE TABLE MAP.E_USEFUL_FIELDS (FIELD_NAME VARCHAR(50), FIELD_VALUE VARCHAR(100));
    INSERT INTO MAP.E_USEFUL_FIELDS (FIELD_NAME, FIELD_VALUE)
    SELECT 'COMPANY_ID',                'XXX'                                                                               UNION ALL
    SELECT 'DEFAULT_GL_OUTAGE_ACCOUNT', 'XXXX'                                                                              UNION ALL
    SELECT 'GL01_BALANCE_END',          CONVERT(VARCHAR(10), DATEFROMPARTS(YEAR(GETDATE()) - 2, 12, 31), 23)                UNION ALL
    SELECT 'GL02_MONTHLY_START',        CONVERT(VARCHAR(10), DATEFROMPARTS(YEAR(GETDATE()) - 1,  1,  1), 23)                UNION ALL
    SELECT 'GL02_MONTHLY_STOP',         CONVERT(VARCHAR(10), DATEFROMPARTS(YEAR(GETDATE()) - 1, 12, 31), 23)                UNION ALL
    SELECT 'GL03_DETAIL_START',         CONVERT(VARCHAR(10), DATEFROMPARTS(YEAR(GETDATE()),      1,  1), 23)                UNION ALL
    SELECT 'GL03_DETAIL_STOP',          CONVERT(VARCHAR(10), EOMONTH(DATEADD(MONTH, -1, GETDATE())), 23);
END
GO
