--INVENTORY ITEM TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_ITEM') BEGIN
CREATE TABLE MAP.T_TRANS_ITEM (DATA_FOLDER_ID VARCHAR(50), LEGACY_ITEM_ID VARCHAR(50), NEW_ITEM_ID VARCHAR(50));
END
GO
