--CLASS TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_CLASS') BEGIN
CREATE TABLE MAP.T_TRANS_CLASS (DATA_FOLDER_ID VARCHAR(50), LEGACY_CLASS_ID VARCHAR(50), NEW_CLASS_ID VARCHAR(50));
END
GO
