--WAREHOUSE TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'MAP' AND TABLE_NAME = 'T_TRANS_WAREHOUSE') BEGIN
CREATE TABLE MAP.T_TRANS_WAREHOUSE (DATA_FOLDER_ID VARCHAR(50), LEGACY_WAREHOUSE_ID VARCHAR(50), NEW_WAREHOUSE_ID VARCHAR(50));
END
GO
